### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Evelyn-H** [Shmuma/rl#2]
Hello,

I'm doing my thesis on Rubik's cube solving with DL, mainly based on [this paper](https://arxiv.org/abs/1805.07470).
Your article and code have been very valuable so far and definitely made my life easier. Though, just to make sure (and because this repo doesn't have a license listed), is it okay if I use your code and cite your article in my thesis?

Thanks!
 -- Evelyn

**Comment by Shmuma** [comment]
Hi! 

Good point, will put GPL v3 license in the repo. Success with your thesis!
